version: '3.8'
services:
  hastebin:
    build: .
    container_name: hastebin
    volumes:
      - ./haste-data:/usr/src/app/data
    environment:
      - STORAGE_TYPE=file
      - STORAGE_FILEPATH=./data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hastebin.rule=Host(`bin.koen02.nl`)"
      - "traefik.http.routers.hastebin.entrypoints=websecure"
      - "traefik.http.routers.hastebin.tls.certresolver=mytlschallenge"
      - "traefik.http.services.hastebin.loadbalancer.server.port=7777"

networks:
  default:
    external:
      name: proxy
